git:
  paging:
    colorArg: always
    pager: delta --dark --paging=never --side-by-side

gui:
  theme:
    selectedLineBgColor:
      - red
    defaultFgColor:
      - white
os:
  editPreset: 'nvim'
