git:
  paging:
    colorArg: always
    pager: delta --dark --paging=never --side-by-side

gui:
  sidePanelWidth: 0.20
  theme:
    activeBorderColor:
      - "#f5e0dc"
      - bold
    inactiveBorderColor:
      - "#a6adc8"
    optionsTextColor:
      - "#89b4fa"
    selectedLineBgColor:
      - "#313244"
    cherryPickedCommitBgColor:
      - "#45475a"
    cherryPickedCommitFgColor:
      - "#f5e0dc"
    unstagedChangesColor:
      - "#f38ba8"
    defaultFgColor:
      - "#cdd6f4"
    searchingActiveBorderColor:
      - "#f9e2af"
authorColors:
  "*": "#b4befe"

os:
  editPreset: "nvim"

keybinding:
  commits:
    viewResetOptions: "D"
  universal:
    gotoTop: "g"
    gotoBottom: "G"
  stash:
    popStash: "s"
