git:
  paging:
    colorArg: always
    pager: delta --dark --paging=never --side-by-side

gui:
  sidePanelWidth: 0.2
  mainPanelSplitMode: horizontal
  expandFocusedSidePanel: true
  border: "single"
  theme:
    activeBorderColor:
      - "#ebbcba"
      - bold
    inactiveBorderColor:
      - "#333333"
    optionsTextColor:
      - "#9ccfd8"
    selectedLineBgColor:
      - "#44415a"
    selectedRangeBgColor:
      - "#26233a"
    cherryPickedCommitBgColor:
      - "#31748f"
    cherryPickedCommitFgColor:
      - "#e0def4"
    unstagedChangesColor:
      - "#eb6f92"
    defaultFgColor:
      - "#e0def4"
    searchingActiveBorderColor:
      - "#f6c177"
  "*": "#b4befe"

os:
  editPreset: "nvim"

keybinding:
  commits:
    viewResetOptions: "D"
  universal:
    gotoTop: "g"
    gotoBottom: "G"
  stash:
    popStash: "s"
